all: docker go imagemagick java jenkins puppet ruby vars xvfb yq

vars:
	@cat $@
	
docker: vars
	@cat $@

go: vars
	@cat $@

imagemagick: vars
	@cat $@

java: vars
	@cat $@

jenkins: vars java
	@cat $@

puppet: vars
	@cat $@

ruby: vars
	@cat $@

xvfb: vars
	@cat $@

yq: vars
	@cat $@
