all: docker go imagemagick java jenkins puppet ruby vars xvfb yq

docker: vars
	cat $@
go: vars
	cat $@
imagemagick: vars
	cat $@
java: vars
	cat $@
jenkins: vars java
	cat $@
puppet: vars
	cat $@
ruby: vars
	cat $@
vars:
	cat $@
xvfb: vars
	cat $@
yq: vars
	cat $@
